export {default as Dashboard} from './Dashboard.jsx'
export {default as AppWidget} from './AppWidget.jsx'
export {default as Login} from './Login.jsx'
export {default as Signup} from './Signup.jsx'
export {default as SidePanel} from './SidePanel.jsx'
export {default as HeroHome} from './partials/HeroHome.jsx'
export {default as Header} from './partials/Header.jsx'
export {default as Footer} from './partials/footer.jsx'
export {default as Navbar} from './partials/Navbar.jsx'

